spring:
  application:
    name: EurekaClient
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: kafka
    kafka:
      topic: zipkin
      bootstrap-servers: localhost:9092

server:
  port: 28080

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30 #租期更新时间间隔
    lease-expiration-duration-in-seconds: 90 #租期到期时间（默认90秒）
  client:
    registry-fetch-interval-seconds: 5 # 间隔多久去拉取服务注册信息
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  config:
    classpath: logback-spring.xml
  path: /data/logs/${spring.application.name}